### ISSUE TITLE
Rename the PyPi package

### ISSUE THREAD

**Issue by linevych** [linevich/django-search-admin-autocomplete#2]
There is a typo in PyPi package name: django-search-admin-autcomplete
https://pypi.python.org/pypi/django-search-admin-autcomplete/0.1

**Comment by diegofcoelho** [comment]
fixed?

**Comment by linevych** [comment]
Not yet, will try to fix in next few days.

**Comment by linevych** [comment]
Fixed: https://pypi.python.org/pypi/django-search-admin-autocomplete
